# Generated by Django 5.2.5 on 2025-08-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alternative_contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
