# Generated by Django 5.2.5 on 2025-09-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile_alternative_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='application_id',
            field=models.CharField(default='D9BCA7', max_length=6, unique=True),
        ),
    ]
