# Generated by Django 5.2.5 on 2025-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_registration_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='application_id',
            field=models.CharField(default='E3F8C6', max_length=6, unique=True),
        ),
    ]
