# Generated by Django 5.2.5 on 2025-09-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_registration_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loan_amount',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='loan_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='application_id',
            field=models.CharField(default='1973F5', max_length=6, unique=True),
        ),
    ]
