# Generated by Django 5.2.5 on 2025-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_profile_loan_amount_profile_loan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='application_id',
            field=models.CharField(default='C513D1', max_length=6, unique=True),
        ),
    ]
